#define NUMLINE 8
#define NUMCOL 8
#define FRAMETOSKIP 10

#define SSI_FRAME_MAX_PAYLOAD_SIZE 255
#define SSI_FRAME_HEADER_SIZE 3
#define SSI_FRAME_FOOTER_SIZE 2
#define SSI_FRAME_OVERHEAD_SIZE (SSI_FRAME_HEADER_SIZE + SSI_FRAME_FOOTER_SIZE)
#define SSI_FRAME_MAX_LENGTH (SSI_FRAME_MAX_PAYLOAD_SIZE + SSI_FRAME_OVERHEAD_SIZE)

#define SSI_FRAME_SOF           0xFE
#define SSI_FRAME_SOF_INDEX     0
#define SSI_FRAME_LEN_INDEX     1
#define SSI_FRAME_NOT_LEN_INDEX 2 
#define SSI_FRAME_ADDR_INDEX    3 
#define SSI_FRAME_CMD_INDEX     4
#define SSI_FRAME_SOP_INDEX     5